http:
  port: 8090
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  accounts:
    host: '*'
    paths: '/accounts/*'
  authentication:
    host: '*'
    paths: '/authentication/*'
  smp:
    host: '*'
    paths: '/smp/*'
  emails:
    host: '*'
    paths: '/emails/*'
  university:
    host: '*'
    paths: '/university/*'
  upload:
    host: '*'
    paths: '/upload/*'
  search:
    host: '*'
    paths: '/search/*'
serviceEndpoints:
  accountsStudents:
    url: 'https://network-accounts-prod.herokuapp.com/'
  authentication:
    url: 'https://network-authentication-prod.herokuapp.com/'
  smp:
    url: 'https://network-socialmarketplace-prod.herokuapp.com/'
  emails:
    url: 'https://network-emails-prod.herokuapp.com/'
  university:
    url: 'https://network-university-prod.herokuapp.com/'
  upload:
    url: 'https://network-upload-prod.herokuapp.com/'
  search:
    url: 'https://network-search-prod.herokuapp.com/'
policies:
#  - basic-auth
#  - cors
#  - expression
#  - key-auth
#  - log
#  - oauth2
  - proxy
#  - rate-limit
pipelines:
  - name: accounts
    apiEndpoints:
      - accounts
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: accountsStudents
              changeOrigin: true
  - name: authentication
    apiEndpoints:
      - authentication
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: authentication
              changeOrigin: true
  - name: smp
    apiEndpoints:
      - smp
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: smp
              changeOrigin: true
  - name: emails
    apiEndpoints:
      - emails
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: emails
              changeOrigin: true
  - name: university
    apiEndpoints:
      - university
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: university
              changeOrigin: true
  - name: upload
    apiEndpoints:
      - upload
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: upload
              changeOrigin: true
  - name: search
    apiEndpoints:
      - search
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: search
              changeOrigin: true
